name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  publish-linux-64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish Self Contained
      run: dotnet publish --self-contained --configuration Release --os linux --arch x64 --output "artifacts/linux-x64/self-contained"
    - name: Publish to GitHub Self Contained
      uses: actions/upload-artifact@v3
      with:
        name: linux-x64-self-contained
        path: artifacts/linux-x64/self-contained/
    - name: Publish NET Runtime dependent
      run: dotnet publish --configuration Release --os linux --arch x64 --output "artifacts/linux-x64/net"
    - name: Publish to GitHub NET Runtime dependent
      uses: actions/upload-artifact@v3
      with:
        name: linux-x64
        path: artifacts/linux-x64/net/

  publish-windows-64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish Self Contained
      run: dotnet publish --self-contained --configuration Release --os win --arch x64 --output "artifacts/win-x64/self-contained"
    - name: Publish to GitHub Self Contained
      uses: actions/upload-artifact@v3
      with:
        name: windows-x64-self-contained
        path: artifacts/win-x64/self-contained/
    - name: Publish NET Runtime dependent
      run: dotnet publish --configuration Release --os win --arch x64 --output "artifacts/win-x64/net"
    - name: Publish to GitHub NET Runtime dependent
      uses: actions/upload-artifact@v3
      with:
        name: windows-x64
        path: artifacts/win-x64/net/
